### ISSUE TITLE
Implement Language Select UI

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#490]
## Description

Now that we have implemented translations for the content we control, we want to enable our users to change the language manually.

## Tasks

- [ ] Create a language dropdown in the header (see screenshot below)
   - [ ] move the logo directly to the right of the main menu button
   - [ ] place language selector to the right of the temperature
- [ ] Ensure the language dropdown only has two languages available, "English" and "Español"
   - these options do not need to be localized
- [ ] When the user selects a language, all content in the application is translated to that selected language
   - This does not apply to the provider portal (anything at https://upswyng.org/provider)
   - If there is some content that isn't translated, we'll create a separate issue to fix those

![example of language selector](https://user-images.githubusercontent.com/6598084/132274790-d623e4d7-f16f-4b28-84c3-b0a14c6705ff.png)

## Tech Notes

- use the standard version of the [MUI native select](https://material-ui.com/api/native-select/)
   - For this issue, don't worry about the discrepancies between the screenshot and what MUI provides. Just focus on the styling of the header with the newly added select
- [tutorial for toggling languages](https://react.i18next.com/legacy-v9/step-by-step-guide#d-let-the-user-toggle-the-language)

**Comment by jacobvenable** [comment]
Being taken on by @Sunset05
