### ISSUE TITLE
Implement search feature

### ISSUE THREAD

**Issue by jacobvenable** [CodeForBoulder/upswyng#9]
We'll need to determine how we'll search the data. Firebase [recommends using a third-party service](https://firebase.google.com/docs/firestore/solutions/search) for full-text search.

## TODO

- [ ] complete dependent issue, #28 
- [ ] determine how we will implement search
- [ ] create final designs for the search feature
- [ ] implement the search feature

## Design

Currently, the wireframe for the location of search can be found on the home page, #26, and will list out services in a resource list page, #28.

While we build the infrastructure, we'll need final mocks for the search module.

## Algolia

[Algolia](https://www.algolia.com) could be a good contender that has [directions](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/tutorials/firebase-algolia/) on implementing with Firebase and has a [discounted plan](https://www.algolia.com/for-open-source) for non-profits. Part them allowing to use Algolia for free will include having something like "**Search by Algolia**" placed near or on our search feature.

**Comment by jacobvenable** [comment]
I have sent an application to receive non-profit status with Algolia. I'll update this issue once I get a response, but I believe our group should qualify.

**Comment by jacobvenable** [comment]
This was closed with #83 and #108 .
